// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_3.Contexts;

namespace WebAPI_3.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200918003422_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI_3.Models.Producto", b =>
                {
                    b.Property<string>("pro_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("pro_cantidad");

                    b.Property<string>("pro_descripcion");

                    b.Property<byte[]>("pro_img");

                    b.Property<string>("pro_nombre");

                    b.Property<decimal>("pro_precio");

                    b.HasKey("pro_id");

                    b.ToTable("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
